# Generated by Django 5.1.6 on 2025-03-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'entries'},
        ),
    ]
