# Generated by Django 5.1.6 on 2025-03-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_logs', '0002_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
