# Generated by Django 5.1.6 on 2025-03-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_logs', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
