# Generated by Django 4.2.20 on 2025-03-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_logs', '0005_entry_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='student',
            new_name='owner',
        ),
    ]
